[dubbo.application]
name="dubbo-go"
module=""
version="1.0.0"
owner="zhaoyunxing"

[dubbo.registries.nacos]
protocol="nacos"
timeout="5s"
group="dev"
address="127.0.0.1:8848"

[dubbo.registries.zk]
protocol="zk"
timeout="5s"
group="dev"
address="127.0.0.1:2818"

[dubbo.provider.services.hello-service]
interface="org.dubbo.service.HelloService"
registry=["nacos","zk"]

[dubbo.provider.services.order-service]
interface="org.dubbo.service.HelloService"
registry=["nacos"]