dubbo:
  application:
    name: dubbo-go
    module: local
    version: 1.0.0
    owner: zhaoyunxing
  registries:
    nacos:
      protocol: nacos
      timeout: 5s
      group: dev
      address: 127.0.0.1:8848
    zk:
      protocol: zk
      group: dev
      address: 127.0.0.1:2181
  provider:
    check: false
    services:
      hello-service:
        interface: org.dubbo.service.HelloService
        registry: nacos
