dubbo:
  application:
    module: local
    name: dubbo-go
    owner: zhaoyunxing
    version: 1.0.0
  provider:
    check: false
    services:
      hello-service:
        interface: org.dubbo.service.HelloService
        registry: nacos
  registries:
    nacos:
      address: nacos://127.0.0.1:8848
      group: dev
      protocol: nacos
      timeout: 5s
    zk:
      address: 127.0.0.1:2181
      group: dev
      protocol: zk
