dubbo:
  application:
    name: dubbo-go
    module: local
    version: 1.0.0
    owner: zhaoyunxing
  registries:
    nacos:
      protocol: nacos
      timeout: 5s
      group: dev
      address: nacos://127.0.0.1:8848
    zk:
      protocol: zk
      timeout: ""
      group: dev
      address: 127.0.0.1:2181
  provider:
    check: false
    register: false
    services:
      hello-service:
        id: ""
        registry:
        - nacos
        register: false
        load-balance: ""
        methods: {}
